#python run_search.py -p 1 -s 1 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 2 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 3 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 4 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 5 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 6 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 7 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 8 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 9 >>output_problem1.txt 2>&1
#python run_search.py -p 1 -s 10 >>output_problem1.txt 2>&1
#python run_search.py -p 2 -s 1 >>output_problem2.txt 2>&1
##python run_search.py -p 2 -s 2 >>output_problem2.txt 2>&1
#python run_search.py -p 2 -s 3 >>output_problem2.txt 2>&1
##python run_search.py -p 2 -s 4 >>output_problem2.txt 2>&1
#python run_search.py -p 2 -s 5 >>output_problem2.txt 2>&1
##python run_search.py -p 2 -s 6 >>output_problem2.txt 2>&1
##python run_search.py -p 2 -s 7 >>output_problem2.txt 2>&1
#python run_search.py -p 2 -s 8 >>output_problem2.txt 2>&1
#python run_search.py -p 2 -s 9 >>output_problem2.txt 2>&1
#python run_search.py -p 2 -s 10 >>output_problem2.txt 2>&1
python run_search.py -p 3 -s 1 >>output_problem3.txt 2>&1
#python run_search.py -p 3 -s 2 >>output_problem3.txt 2>&1
python run_search.py -p 3 -s 3 >>output_problem3.txt 2>&1
#python run_search.py -p 3 -s 4 >>output_problem3.txt 2>&1
python run_search.py -p 3 -s 5 >>output_problem3.txt 2>&1
#python run_search.py -p 3 -s 6 >>output_problem3.txt 2>&1
#python run_search.py -p 3 -s 7 >>output_problem3.txt 2>&1
python run_search.py -p 3 -s 8 >>output_problem3.txt 2>&1
python run_search.py -p 3 -s 9 >>output_problem3.txt 2>&1
python run_search.py -p 3 -s 10 >>output_problem3.txt 2>&1
